include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    curly_braces_in_flow_control_structures: ignore
    no_leading_underscores_for_local_identifiers: ignore

  exclude:
    - lib/src/ffi/bindings.gen.dart

formatter:
  page_width: 120